### ISSUE TITLE
pip installing uwsgi fails, upgrade to 2.0.13

### ISSUE THREAD

**Issue by barbeque** [wagtail/wagtaildemo#107]
When I tried to lay out the requirements file on my install of ubuntu 16.10, uwsgi fails to build because of the issue reported here: https://github.com/unbit/uwsgi/issues/1247

I upgraded the requirements.txt file to =2.0.13 so that it would build, but I am unsure if I should submit a pull request to update those requirements here, since the comment in the requirements file says it is for your heroku setup and I am not familiar enough to know why that specific version was chosen.

I can submit a pull request with the change if you wish, but don't know how to test if it will break your instance.

**Comment by gasman** [comment]
Thanks for the report @barbeque! I've now updated requirements.txt to install the latest 2.0.x version, and confirmed that the heroku build still completes successfully.
