### ISSUE TITLE
Recomended way of doing page comparison using urls as identifiers

### ISSUE THREAD

**Issue by nicoepp** [wagtail/wagtaildemo#114]
I'm currently modifying our code related to menu generation. In the past we had some problems when trying to mark which of the pages was the active one, so I took the `top_menu` tag from wagtail_demo as inspiration to rewrite the code.

This is the line which does the comparison to mark the calling page as the active one:
` menuitem.active = (calling_page.url.startswith(menuitem.url)
                           if calling_page else False)`

My question is, considering [this](http://docs.wagtail.io/en/v1.11.1/releases/1.11.html#caching-of-site-level-url-information-throughout-the-request-cycle) advice about caching of url information from the wagtail 1.11 release notes, is it still recomended using the `url` property instead of `get_url(request=request)` when doing this type of comparison or should this code be updated?

**Comment by gasman** [comment]
It should be updated, yes. Constructing URLs just to do a comparison is actually needlessly inefficient - comparing the `path` field of the two pages would be much better.
